// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApl40nnBCOuUo7IbeIRxHNntEza7VVgJY',
    appId: '1:678389198909:web:ac9e87f31cbc4fcc80ba54',
    messagingSenderId: '678389198909',
    projectId: 'chatapp-a71a6',
    authDomain: 'chatapp-a71a6.firebaseapp.com',
    storageBucket: 'chatapp-a71a6.appspot.com',
    measurementId: 'G-D809GKHRQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAacaCadql7Mx5pfg1TWdsk8s15M7Yk-Gs',
    appId: '1:678389198909:android:9e1abee1d7c2e5a480ba54',
    messagingSenderId: '678389198909',
    projectId: 'chatapp-a71a6',
    storageBucket: 'chatapp-a71a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsj9YC17qGW7z6iGOUumu0vpafkaPhiic',
    appId: '1:678389198909:ios:d56dc095ec7b90ab80ba54',
    messagingSenderId: '678389198909',
    projectId: 'chatapp-a71a6',
    storageBucket: 'chatapp-a71a6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsj9YC17qGW7z6iGOUumu0vpafkaPhiic',
    appId: '1:678389198909:ios:a427a83cc71785f180ba54',
    messagingSenderId: '678389198909',
    projectId: 'chatapp-a71a6',
    storageBucket: 'chatapp-a71a6.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
